server:
  port: 9002
spring:
  application:
    name: cloudalibaba-provider-payment
  cloud:
    nacos:
      discovery:
#        nginx的1111端口，做集群
        server-addr: 120.24.35.246:1111

management:
  endpoints:
    web:
      exposure:
        include: "*"
