server:
  port: 8802


spring:
  application:
    name: cloud-strem-receive
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit:  #表示绑定的名称
          type: rabbit  #消费组件类型
          environment:  #设置rabbit的相关的环境配置
            spring:
              rabbitmq:
                host: 120.24.35.246
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        input: #这个名称是一个通道的名称
          destination: studyExchange #表示要使用的Exchange名称定义
          content-type: application/json #设置消息类型，本次为json，文本设置“text/plain”
          default-binder: defaultRabbit #设置要绑定服务的具体设置
          group: zwf #分组

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    lease-expiration-duration-in-seconds: 5 #如果超过了5秒的时间间隔（默认90秒）
    lease-renewal-interval-in-seconds: 2 #设置心跳间隔（默认是30秒）
    instance-id: receive-8802.com
    prefer-ip-address: true

