server:
  port: 8002

spring:
  application:
    name: cloud-provide-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment?serverTimezone=UTC
    username: root
    password: 666666

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      集群版
     defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#     defaultZone: http://eureka7002.com:7002/eureka

  instance:
    instance-id: payment8002
    prefer-ip-address: true

mybatis:
#  映射文件位置
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: zwf.springcloud.entities